### ISSUE TITLE
Format of floating axis label - 'error' when horizon populated with 'minute' values  (is %Y-%m-%d %H:%M label possible?)

### ISSUE THREAD

**Issue by marceluk** [kbroman/horizon#5]
Hi Karl,

Great work - I am not sure if there are any other R based horizon charts in active development - but I have found yours very close to what I need (great html widget interactivity).

Despite your example charts being based around whole dates (ie. single value per day), I am able to populate horizon with **minute based values** (eg. 2017-11-01 09:00, 2017-11-01 09:15, 2017-11-01 09:30..), however when I do this the **floating axis label** (top and bottom) shows **unexpected values** (eg. "02:04 AM") - is this something you/I might be able to fix/change?

Marcel.

**Comment by kbroman** [comment]
I'm not too eager to try to dig into this; I found it rather rough going. Maybe look at [d3horizonR](https://timelyportfolio.github.io/d3horizonR/) from @timelyportfolio? But if that doesn't work for you, I could try to get back to this to get it to work for you.

**Comment by marceluk** [comment]
Many thanks for the prompt response. Unfortunately without even axis labels (or interactivity) d3horizonR doesn't look like it will work for me. :(

**Comment by kbroman** [comment]
Ah, I see. Could you get me a version of data like you have in mind, and I'll see what I might need to do to get the present package to work with it?

**Comment by timelyportfolio** [comment]
I could also try to help resolve, but it will be toward end of next week.

**Comment by marceluk** [comment]
Sample data demonstrating problem (borrowing heavily from horizon inbuilt sample data)

```
# Based on the following horizon package (not to be confused with horizon on CRAN)
# install.packages("devtools")
# devtools::install_github("kbroman/horizon")

library(horizon)
library(lubridate)

# example with simulated data
n <- 600  # number of time points
p <- 26   # number of time series

# generate time points every 15 minutes (900 seconds)  
dates <- as.character( seq( lubridate::ymd_hms("2017-10-01 00:00:00"), by=900, length=n) )

# simulate brownian motion, all starting at 0
y <- matrix(0, nrow=n, ncol=p)
y[-1,] <- rnorm((n-1)*p, 0, 0.25)
y <- apply(y, 2, cumsum)

colnames(y) <- letters[1:p]

# make the horizon plot
horizon(dates, y,  date_format = "%Y-%m-%d %H:%M:%S")
```
![horizon_floatinglabelissue](https://user-images.githubusercontent.com/18037852/32319701-63e79612-bfb3-11e7-96bd-68c523a50a9b.png)

**Comment by kbroman** [comment]
I think I've got it. I added arguments `tick_format` and `focus_format` which take strings to represent date/time formats for the top and bottom axis labels and for the date/time at the "focus", respectively.

With your example, you could do something like:

```
horizon(dates, y,  date_format = "%Y-%m-%d %H:%M:%S",
        tick_format="%Y-%m-%d", focus_format="%Y-%m-%d %H:%M")            
```

(Within the javascript, the `context.axis()` has methods `.tickFormat()` and `.focusFormat()` to control these things. I pass them `d3.time.format( format_string )` with the `format_string` if provided.

**Comment by marceluk** [comment]
Thanks. This is better, although I don't understand why the floating label will say something like "2017-10-04 08:06" but the data has 15 minute time points "2017-10-04 08:00" and "2017-10-04 08:15" (but no 08:06).

The first, second and last timepoints - which I understand are used to generate the horizon timeline are..

1. 2017-10-01 00:00:00
2. 2017-10-01 00:15:00
...
600. 2017-10-07 05:45:00

**Comment by kbroman** [comment]
I think [cubism.js](https://square.github.io/cubism/) is doing some interpolation.

I revised things so that when `focus_format` is provided, we find the closest date/time in the data and display that.

**Comment by marceluk** [comment]
Many, many thanks - this now looks great. :)

![horizon_floatinglabelissue_fixed](https://user-images.githubusercontent.com/18037852/32333542-234148ba-bfe0-11e7-8376-e0ba99ea6a06.png)

**Comment by kbroman** [comment]
I'm glad I could get it to work for you. It was not as hard as I had expected.
